-- 0152 — money dates stop being measured on the server's UTC day.
--
-- Found while auditing whether revenue and profit are actually right (Ali
-- asked directly, 2026-08-06). Revenue and profit came back clean: six
-- independent paths agree at MVR 40,921 and four agree on MVR 26,456 of
-- cost, all against the cost LOCKED at each sale. This migration is what the
-- audit turned up instead.
--
-- Male is UTC+5, so from 19:00 UTC onward the Maldives is already tomorrow.
-- Six functions were still asking Postgres for CURRENT_DATE — the server's
-- UTC day — and two of them also cast an order timestamp straight to ::date.
-- Migrations 0123, 0126 and 0130 fixed this same bug class three separate
-- times, each time in one more REPORTING function; none of them touched
-- these six. This is the fourth pass, and it is a sweep rather than another
-- single fix.
--
-- What each one was getting wrong:
--
--   get_receivables_aging     Aged every debt with CURRENT_DATE minus
--                             created_at::date, both sides UTC. A debt could
--                             read a day older or younger than it is, which
--                             is enough to flip the 30- and 60-day buckets
--                             that decide whether Ali is told to chase it.
--                             Currently benign: all 3 outstanding debts are
--                             0 days old, MVR 1,139, all 'current'.
--   set_cash_balance          Stamped the cash-on-hand snapshot with the UTC
--                             date. Counting the till at 1am in Male filed
--                             the figure under yesterday. A money record
--                             under the wrong date.
--   get_cash_forecast         date_trunc('week', CURRENT_DATE) — for five
--                             hours a day this picks the wrong day, and
--                             across a Sunday boundary the wrong WEEK.
--   get_cash_forecast_meta    A 90-day lookback edge, and "how stale is the
--                             cash figure" in days.
--   get_reorder_suggestions   order_by_date, the day Ali is told to place
--                             the next order by.
--   get_sku_reorder_alerts    The days-of-history divisor behind velocity.
--
-- None of these touch revenue or profit. They affect how old a debt looks,
-- which week the cash forecast starts, and when to reorder.
--
-- Every replacement is mechanical: CURRENT_DATE becomes
-- (now() at time zone 'Indian/Maldives')::date, and a bare ::date on a
-- timestamptz becomes (col at time zone 'Indian/Maldives')::date. The bodies
-- below were generated by applying exactly those two substitutions to the
-- live definitions rather than retyped, so nothing else can have drifted.
--
-- Guarded permanently by a structural test in money_rules.test.sql: no
-- function in this database may contain CURRENT_DATE at all. That is what
-- stops a fifth instance, since the previous three fixes each left one more
-- behind.

BEGIN;

CREATE OR REPLACE FUNCTION public.get_receivables_aging()
 RETURNS TABLE(customer_id uuid, customer_name text, phone text, orders_count integer, outstanding_mvr numeric, oldest_days integer, bucket text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  WITH order_totals AS (
    SELECT so.id, so.customer_id,
           COALESCE((so.delivered_at at time zone 'Indian/Maldives')::date, (so.created_at at time zone 'Indian/Maldives')::date) AS due_start,
           COALESCE(SUM(sol.line_total_mvr), 0) AS total
    FROM sales_orders so
    JOIN sales_order_lines sol ON sol.order_id = so.id
    WHERE so.status NOT IN ('draft', 'cancelled')
      AND so.payment_status NOT IN ('paid', 'deposited')
    GROUP BY so.id
  ),
  order_paid AS (
    SELECT op.order_id, COALESCE(SUM(op.amount_mvr), 0) AS paid
    FROM order_payments op
    GROUP BY op.order_id
  ),
  order_returned AS (
    SELECT sr.order_id, COALESCE(SUM(sr.refund_amount_mvr), 0) AS returned
    FROM sales_returns sr
    GROUP BY sr.order_id
  ),
  owed AS (
    SELECT ot.customer_id,
           ot.total - COALESCE(p.paid, 0) - COALESCE(r.returned, 0) AS outstanding,
           ((now() at time zone 'Indian/Maldives')::date - ot.due_start)  AS age_days
    FROM order_totals ot
    LEFT JOIN order_paid     p ON p.order_id = ot.id
    LEFT JOIN order_returned r ON r.order_id = ot.id
    WHERE ot.total - COALESCE(p.paid, 0) - COALESCE(r.returned, 0) > 0.005
  )
  SELECT
    o.customer_id,
    COALESCE(c.name, 'Walk-in / no customer') AS customer_name,
    c.phone,
    COUNT(*)::integer,
    ROUND(SUM(o.outstanding), 2),
    MAX(o.age_days)::integer,
    CASE
      WHEN MAX(o.age_days) > 60 THEN 'overdue'
      WHEN MAX(o.age_days) > 30 THEN 'watch'
      ELSE 'current'
    END
  FROM owed o
  LEFT JOIN customers c ON c.id = o.customer_id
  GROUP BY o.customer_id, c.name, c.phone
  ORDER BY MAX(o.age_days) DESC, SUM(o.outstanding) DESC;
$function$;

CREATE OR REPLACE FUNCTION public.get_cash_forecast(p_weeks integer DEFAULT 13)
 RETURNS TABLE(week_index integer, week_start date, cash_in_mvr numeric, cash_out_mvr numeric, shipment_out_mvr numeric, net_mvr numeric, projected_balance_mvr numeric)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  WITH m AS (SELECT * FROM get_cash_forecast_meta()),
  wk_start AS (SELECT date_trunc('week', (now() at time zone 'Indian/Maldives')::date)::date AS d),   -- this Monday
  weeks AS (
    SELECT gs AS week_index,
           ((SELECT d FROM wk_start) + (gs * 7))::date AS week_start
    FROM generate_series(0, GREATEST(p_weeks, 1) - 1) gs
  ),
  -- Dated open-shipment payables, bucketed into the week they're expected.
  ship AS (
    SELECT date_trunc('week', s.expected_arrival_date)::date AS wstart,
           SUM(CASE WHEN COALESCE(t.landed, 0) > 0 THEN t.landed
                    ELSE COALESCE(t.fob, 0)
                       + COALESCE(s.customs_duty_mvr,0)+COALESCE(s.mpl_charges_mvr,0)
                       + COALESCE(s.agent_fee_mvr,0)+COALESCE(s.last_mile_mvr,0)
                       + COALESCE(s.insurance_mvr,0)+COALESCE(s.other_mvr,0)
                       + COALESCE(s.my_freight_share_usd,0)*COALESCE(s.rate_usd_to_mvr,0)
               END) AS cost
    FROM shipments s
    JOIN LATERAL (
      SELECT COALESCE(SUM(sl.landed_total_mvr), 0) AS landed,
             COALESCE(SUM(sl.fob_total_mvr), 0)    AS fob
      FROM shipment_lines sl WHERE sl.shipment_id = s.id
    ) t ON true
    WHERE s.grn_confirmed_at IS NULL
      AND s.expected_arrival_date IS NOT NULL
      AND s.expected_arrival_date >= (SELECT d FROM wk_start)
    GROUP BY 1
  ),
  rows AS (
    SELECT
      w.week_index, w.week_start,
      -- IN: steady sales run-rate every week, plus outstanding receivables
      -- spread evenly across the first 4 weeks.
      (SELECT weekly_sales_in_mvr FROM m)
        + CASE WHEN w.week_index < 4
               THEN (SELECT receivables_total_mvr FROM m) / 4.0 ELSE 0 END AS cash_in,
      (SELECT weekly_operating_out_mvr FROM m) AS cash_out,
      COALESCE((SELECT sh.cost FROM ship sh WHERE sh.wstart = w.week_start), 0) AS shipment_out
    FROM weeks w
  ),
  netted AS (
    SELECT week_index, week_start, cash_in, cash_out, shipment_out,
           (cash_in - cash_out - shipment_out) AS net
    FROM rows
  )
  SELECT
    week_index, week_start,
    ROUND(cash_in, 2), ROUND(cash_out, 2), ROUND(shipment_out, 2), ROUND(net, 2),
    ROUND((SELECT opening_balance_mvr FROM m)
          + SUM(net) OVER (ORDER BY week_index ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), 2)
  FROM netted
  ORDER BY week_index;
$function$;

CREATE OR REPLACE FUNCTION public.get_cash_forecast_meta()
 RETURNS TABLE(opening_balance_mvr numeric, has_opening boolean, snapshot_as_of date, snapshot_age_days integer, weekly_sales_in_mvr numeric, weekly_operating_out_mvr numeric, receivables_total_mvr numeric, undated_shipment_cost_mvr numeric, undated_shipment_count integer)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  WITH snap AS (
    SELECT balance_mvr, as_of_date
    FROM cash_snapshots ORDER BY as_of_date DESC, created_at DESC LIMIT 1
  ),
  collections AS (
    SELECT COALESCE(SUM(amount_mvr), 0) AS total
    FROM order_payments
    WHERE COALESCE(is_reversal, false) = false
      AND paid_at >= now() - INTERVAL '90 days'
  ),
  opex AS (
    SELECT
      (SELECT COALESCE(SUM(amount_mvr), 0) FROM business_expenses
        WHERE expense_date >= (now() at time zone 'Indian/Maldives')::date - 90)
      + (SELECT COALESCE(SUM(amount_mvr), 0) FROM marketing_spend
        WHERE start_date >= (now() at time zone 'Indian/Maldives')::date - 90) AS total
  ),
  receivables AS (
    SELECT COALESCE(SUM(outstanding_mvr), 0) AS total FROM get_receivables_aging()
  ),
  -- Unconfirmed shipments we can't place on the timeline (no arrival date):
  -- surfaced as a lump so a big undated bill can't hide.
  open_ship AS (
    SELECT COALESCE(SUM(sc.cost), 0) AS cost, COUNT(*)::int AS cnt
    FROM (
      SELECT s.id,
             CASE WHEN COALESCE(SUM(sl.landed_total_mvr), 0) > 0
                    THEN SUM(sl.landed_total_mvr)
                  ELSE COALESCE(SUM(sl.fob_total_mvr), 0)
                     + COALESCE(s.customs_duty_mvr,0)+COALESCE(s.mpl_charges_mvr,0)
                     + COALESCE(s.agent_fee_mvr,0)+COALESCE(s.last_mile_mvr,0)
                     + COALESCE(s.insurance_mvr,0)+COALESCE(s.other_mvr,0)
                     + COALESCE(s.my_freight_share_usd,0)*COALESCE(s.rate_usd_to_mvr,0)
             END AS cost
      FROM shipments s
      LEFT JOIN shipment_lines sl ON sl.shipment_id = s.id
      WHERE s.grn_confirmed_at IS NULL
        AND s.expected_arrival_date IS NULL
      GROUP BY s.id
    ) sc
  )
  SELECT
    COALESCE((SELECT balance_mvr FROM snap), 0),
    (SELECT count(*) FROM snap) > 0,
    (SELECT as_of_date FROM snap),
    CASE WHEN (SELECT as_of_date FROM snap) IS NOT NULL
         THEN ((now() at time zone 'Indian/Maldives')::date - (SELECT as_of_date FROM snap))::int END,
    ROUND((SELECT total FROM collections) / (90.0 / 7.0), 2),
    ROUND((SELECT total FROM opex) / (90.0 / 7.0), 2),
    ROUND((SELECT total FROM receivables), 2),
    ROUND((SELECT cost FROM open_ship), 2),
    (SELECT cnt FROM open_ship);
$function$;

CREATE OR REPLACE FUNCTION public.get_reorder_suggestions(p_lead_weeks numeric DEFAULT 6, p_safety_weeks numeric DEFAULT 4)
 RETURNS TABLE(sku_id uuid, brand_name text, model_name text, variant_display text, internal_code text, stock_pieces numeric, stock_cartons numeric, daily_avg_pieces numeric, dir numeric, cover_days numeric, suggested_pieces numeric, suggested_cartons integer, pcs_per_carton integer, revenue_per_day numeric, status text, supplier_name text, lead_days numeric, order_by_date date, trend text, sold_90d integer)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  WITH
  cover AS (
    SELECT (COALESCE(p_lead_weeks, 6) + COALESCE(p_safety_weeks, 4)) * 7.0 AS cover_days
  ),
  lead_hist AS (
    SELECT sl.sku_id, s.created_at, s.grn_confirmed_at, sup.name AS supplier_name,
           ROW_NUMBER() OVER (PARTITION BY sl.sku_id ORDER BY s.grn_confirmed_at DESC) AS rn
    FROM (SELECT DISTINCT shipment_id, sku_id FROM shipment_lines) sl
    JOIN shipments s ON s.id = sl.shipment_id AND s.grn_confirmed_at IS NOT NULL
    LEFT JOIN suppliers sup ON sup.id = s.supplier_id
  ),
  sku_lead AS (
    SELECT lh.sku_id,
           ROUND((AVG(EXTRACT(epoch FROM (lh.grn_confirmed_at - lh.created_at)) / 86400.0)
                  FILTER (WHERE lh.rn <= 3))::numeric, 0) AS lead_days,
           MAX(lh.supplier_name) FILTER (WHERE lh.rn = 1)  AS supplier_name
    FROM lead_hist lh
    GROUP BY lh.sku_id
  ),
  base AS (
    SELECT a.*, c.cover_days
    FROM get_sku_reorder_alerts() a
    CROSS JOIN cover c
  )
  SELECT
    b.sku_id,
    vs.brand_name,
    vs.model_name,
    vs.variant_display,
    vs.internal_code,
    b.stock_pieces,
    ROUND(b.stock_pieces / NULLIF(vs.pcs_per_carton, 0), 1)              AS stock_cartons,
    b.daily_avg_pieces,
    b.dir,
    b.cover_days,
    GREATEST(0, ROUND(b.daily_avg_pieces * b.cover_days - b.stock_pieces, 0)) AS suggested_pieces,
    CEIL(
      GREATEST(0, b.daily_avg_pieces * b.cover_days - b.stock_pieces)
      / NULLIF(vs.pcs_per_carton, 0)
    )::INTEGER                                                           AS suggested_cartons,
    vs.pcs_per_carton,
    ROUND(b.daily_avg_pieces * COALESCE(vs.selling_price_per_piece_mvr, 0), 2) AS revenue_per_day,
    CASE
      WHEN b.dir IS NOT NULL AND b.dir > 90 THEN 'overstock'
      ELSE b.alert_level
    END                                                                  AS status,
    sl.supplier_name,
    sl.lead_days,
    CASE
      WHEN b.dir IS NOT NULL THEN GREATEST(
        (now() at time zone 'Indian/Maldives')::date,
        (now() at time zone 'Indian/Maldives')::date + (b.dir - COALESCE(sl.lead_days, COALESCE(p_lead_weeks, 6) * 7))::int
      )
    END                                                                  AS order_by_date,
    b.trend,
    b.sold_90d
  FROM base b
  JOIN v_skus vs ON vs.id = b.sku_id
  LEFT JOIN sku_lead sl ON sl.sku_id = b.sku_id
  ORDER BY
    CASE
      WHEN b.dir IS NOT NULL AND b.dir > 90 THEN 2
      WHEN b.alert_level = 'critical' THEN 0
      WHEN b.alert_level = 'low'      THEN 1
      ELSE 3
    END,
    (b.daily_avg_pieces * COALESCE(vs.selling_price_per_piece_mvr, 0)) DESC;
$function$;

CREATE OR REPLACE FUNCTION public.get_sku_reorder_alerts()
 RETURNS TABLE(sku_id uuid, stock_pieces numeric, daily_avg_pieces numeric, dir numeric, reorder_point_pcs numeric, alert_level text, daily_avg_recent numeric, daily_avg_base numeric, trend text, sold_90d integer)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  WITH
  stock AS (
    SELECT sm.sku_id,
      COALESCE(SUM(stock_signed_delta(sm.movement_type, sm.qty_pieces)), 0) AS stock_pieces
    FROM stock_movements sm
    GROUP BY sm.sku_id
  ),
  velocity AS (
    SELECT sm.sku_id,
      SUM(sm.qty_pieces) FILTER (WHERE sm.created_at >= NOW() - INTERVAL '30 days')::numeric / 30.0 AS v30,
      SUM(sm.qty_pieces)  AS units_90,
      MIN(sm.created_at)  AS first_out
    FROM stock_movements sm
    JOIN sales_orders so ON so.id = sm.source_id
    WHERE sm.movement_type = 'out'
      AND sm.source_type   = 'sales_order'
      AND sm.created_at   >= NOW() - INTERVAL '90 days'
      AND so.status NOT IN ('draft', 'cancelled')
    GROUP BY sm.sku_id
  ),
  blended AS (
    SELECT v.sku_id,
      COALESCE(v.v30, 0) AS v30,
      COALESCE(v.units_90, 0) AS units_90,
      CASE WHEN v.first_out IS NOT NULL
        THEN COALESCE(v.units_90, 0)
             / LEAST(90.0, GREATEST(1.0, ((now() at time zone 'Indian/Maldives')::date - (v.first_out at time zone 'Indian/Maldives')::date) + 1))
        ELSE 0 END AS v_base
    FROM velocity v
  ),
  scored AS (
    SELECT b.sku_id, b.v30, b.v_base, b.units_90,
      ROUND(
        b.v30 * (1 + LEAST(0.4, GREATEST(0.0,
          CASE WHEN b.v_base > 0 THEN b.v30 / b.v_base - 1 ELSE 0 END) * 0.5)),
        4) AS daily_fwd
    FROM blended b
  )
  SELECT
    s.id AS sku_id,
    GREATEST(COALESCE(st.stock_pieces, 0), 0) AS stock_pieces,
    COALESCE(b.daily_fwd, 0) AS daily_avg_pieces,
    CASE WHEN COALESCE(b.daily_fwd, 0) > 0
      THEN ROUND(GREATEST(COALESCE(st.stock_pieces, 0), 0) / b.daily_fwd, 1)
      ELSE NULL END AS dir,
    ROUND(COALESCE(b.daily_fwd, 0) * 21, 0) AS reorder_point_pcs,
    CASE
      WHEN COALESCE(b.daily_fwd, 0) <= 0 THEN 'ok'
      WHEN GREATEST(COALESCE(st.stock_pieces, 0), 0) <= 0 THEN 'out'
      WHEN GREATEST(COALESCE(st.stock_pieces, 0), 0) / b.daily_fwd < 7  THEN 'critical'
      WHEN GREATEST(COALESCE(st.stock_pieces, 0), 0) / b.daily_fwd < 14 THEN 'low'
      ELSE 'ok'
    END AS alert_level,
    ROUND(COALESCE(b.v30, 0), 4)    AS daily_avg_recent,
    ROUND(COALESCE(b.v_base, 0), 4) AS daily_avg_base,
    CASE
      WHEN COALESCE(b.units_90, 0) < 6 OR COALESCE(b.v_base, 0) <= 0 THEN 'steady'
      WHEN b.v30 >= b.v_base * 1.3 THEN 'rising'
      WHEN b.v30 <= b.v_base * 0.7 THEN 'falling'
      ELSE 'steady'
    END AS trend,
    COALESCE(b.units_90, 0)::int AS sold_90d
  FROM skus s
  LEFT JOIN stock   st ON st.sku_id = s.id
  LEFT JOIN scored  b  ON b.sku_id  = s.id
  WHERE s.is_active = TRUE
    AND (COALESCE(st.stock_pieces, 0) > 0 OR COALESCE(b.daily_fwd, 0) > 0);
$function$;

CREATE OR REPLACE FUNCTION public.set_cash_balance(p_amount numeric, p_as_of date DEFAULT (now() at time zone 'Indian/Maldives')::date, p_note text DEFAULT NULL::text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_id   uuid;
  v_prev numeric;
BEGIN
  IF NOT is_admin_or_manager() THEN
    RAISE EXCEPTION 'Not authorised to set the cash balance';
  END IF;
  IF p_amount IS NULL OR p_amount < 0 THEN
    RAISE EXCEPTION 'Cash on hand must be zero or more';
  END IF;

  SELECT balance_mvr INTO v_prev
  FROM cash_snapshots ORDER BY as_of_date DESC, created_at DESC LIMIT 1;

  INSERT INTO cash_snapshots (balance_mvr, as_of_date, note, created_by)
  VALUES (ROUND(p_amount, 2), COALESCE(p_as_of, (now() at time zone 'Indian/Maldives')::date),
          NULLIF(btrim(p_note), ''), (SELECT auth.uid()))
  RETURNING id INTO v_id;

  INSERT INTO audit_log (table_name, record_id, action, field_name,
                         old_value, new_value, reason, changed_by)
  VALUES ('cash_snapshots', v_id, 'insert', 'balance_mvr',
          v_prev::text, ROUND(p_amount, 2)::text,
          'Cash on hand set for ' || COALESCE(p_as_of, (now() at time zone 'Indian/Maldives')::date)::text,
          (SELECT auth.uid()));

  RETURN v_id;
END;
$function$;

COMMIT;
